use std::{fs, path::Path, process::Command};

pub const DUMP_VARIABLES: [&str; 4] = [
    "ARES_DUMP_LMAP2",
    "ARES_DUMP_EBLOCKS",
    "ARES_DUMP_LMAP",
    "ARES_DUMP_TIMES",
];

pub fn slice(directory: &Path, name: &str, variables: &[(&str, &Path)]) -> Vec<u8> {
    let output = directory.join(format!("{name}.gcode"));
    let project =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/processor_output_isolation/project.3mf");
    let mut command = Command::new(env!("CARGO_BIN_EXE_ares"));
    command.env_remove("ARES_ESTIMATE_ONLY");
    for name in DUMP_VARIABLES {
        command.env_remove(name);
    }
    for &(name, value) in variables {
        command.env(name, value);
    }
    let result = command
        .arg("slice")
        .arg(&project)
        .arg("-o")
        .arg(&output)
        .output()
        .unwrap();
    assert!(
        result.status.success(),
        "{command:?}: {}\nstdout: {}\nstderr: {}",
        result.status,
        String::from_utf8_lossy(&result.stdout),
        String::from_utf8_lossy(&result.stderr)
    );
    assert!(result.stdout.is_empty(), "unexpected CLI stdout");
    assert!(result.stderr.is_empty(), "unexpected CLI stderr");
    fs::read(output).unwrap()
}

pub fn assert_same_gcode(expected: &[u8], actual: &[u8]) {
    let expected = normalize_generator_timestamp(expected);
    let actual = normalize_generator_timestamp(actual);
    assert!(
        expected == actual,
        "complete G-code differs: lengths {}/{}, first differing byte {:?}",
        expected.len(),
        actual.len(),
        expected.iter().zip(&actual).position(|(a, b)| a != b)
    );
}

fn normalize_generator_timestamp(bytes: &[u8]) -> Vec<u8> {
    let text = std::str::from_utf8(bytes).unwrap();
    let pattern = regex::Regex::new(
        r"(?m)^; generated by Ares 2\.4\.2 on (\d{4}-\d{2}-\d{2}) at (\d{2}:\d{2}:\d{2})$",
    )
    .unwrap();
    let matches = pattern.captures_iter(text).collect::<Vec<_>>();
    assert_eq!(matches.len(), 1, "expected one valid Ares generator line");
    let timestamp = format!("{}T{}", &matches[0][1], &matches[0][2]);
    timestamp.parse::<jiff::civil::DateTime>().unwrap();
    pattern
        .replace(text, "; generated by Ares 2.4.2 on <TIMESTAMP>")
        .into_owned()
        .into_bytes()
}
