//! Comparator contracts, not Ares slicing passes. Real records come from the
//! committed classic stream; absent arc/multi-object streams below are synthetic.
//! Orca 8500fcd: GCode::do_export (config/statistics/object boundaries),
//! GCodeWriter::{travel_to_xy,travel_to_z,extrude_to_xy,extrude_arc_to_xy,
//! set_acceleration,set_temperature,set_fan,retract}, GCodeProcessor::run_post_process.
use super::compare_ordered_bytes_generator_only as compare;

const ORCA: &str = "; generated by OrcaSlicer 2.4.2 on 2026-09-08 at 04:26:03\n";
const ARES: &str = "; generated by Ares 2.4.2 on 2030-12-31 at 23:59:58\n";
const CLASSIC: &str = include_str!("../../../../tests/parity/replay/ender3-classic.orca.gcode");

fn reject(reference: &str, baseline: &str, changed: &str, label: &str) {
    assert_ne!(baseline, changed, "mutation missed: {label}");
    let error = compare(reference.as_bytes(), changed.as_bytes()).unwrap_err();
    assert!(
        error.contains("first difference at byte"),
        "{label}: {error}"
    );
}

fn mutations(reference: &str, first: &str, second: &str, changed: &str, label: &str) {
    // Header substitution constructs only a comparator input, never an Orca replay.
    assert_eq!(reference.matches(ORCA).count(), 1);
    let baseline = reference.replacen(ORCA, ARES, 1);
    compare(reference.as_bytes(), baseline.as_bytes()).unwrap();
    let lines: Vec<_> = baseline.split_inclusive('\n').collect();
    let i = lines.iter().position(|line| *line == first).unwrap();
    let j = lines.iter().position(|line| *line == second).unwrap();
    assert!(i < j, "ordered distinct anchors: {label}");
    assert_ne!(first, second);
    assert_ne!(first, changed);
    let mut replacement = lines.clone();
    replacement[i] = changed;
    reject(
        reference,
        &baseline,
        &replacement.concat(),
        &format!("{label}/change"),
    );
    let mut deletion = lines.clone();
    deletion.remove(i);
    assert_eq!(deletion.len() + 1, lines.len());
    reject(
        reference,
        &baseline,
        &deletion.concat(),
        &format!("{label}/delete"),
    );
    let mut reordered = lines;
    reordered.swap(i, j);
    assert_eq!((reordered[i], reordered[j]), (second, first));
    reject(
        reference,
        &baseline,
        &reordered.concat(),
        &format!("{label}/reorder"),
    );
}

#[test]
fn gcode_writer_and_do_export_real_records_reject_33_mutations() {
    for (label, first, second, changed) in [
        (
            "XY travel",
            "G1 X2 Y10 F3000\n",
            "G1 X2.3 F5000\n",
            "G1 X2 Y10.001 F3000\n",
        ),
        ("Z", "G1 Z.6\n", "G1 Z.2\n", "G1 Z.601\n"),
        (
            "E retract",
            "G1 E-4 F3600\n",
            "G1 E4 F2400\n",
            "G1 E-4.001 F3600\n",
        ),
        ("F", "G1 F3000\n", "G1 F1800\n", "G1 F3001\n"),
        (
            "acceleration",
            "M201 X500 Y500 Z100 E5000\n",
            "M204 P500 R1000 T500\n",
            "M201 X501 Y500 Z100 E5000\n",
        ),
        (
            "temperature",
            "M190 S60 ; wait for bed temp to stabilize\n",
            "M109 S220 ; wait for nozzle temp to stabilize\n",
            "M140 S60 ; wait for bed temp to stabilize\n",
        ),
        ("fan", "M106 S0\n", "M106 S255\n", "M106 S1\n"),
        (
            "lifecycle",
            "G90 ; use absolute coordinates\n",
            "M83 ; extruder relative mode\n",
            "G91 ; use absolute coordinates\n",
        ),
        ("M73", "M73 P4 R8\n", "M73 P6 R8\n", "M73 P2 R8\n"),
        (
            "config",
            "; enable_arc_fitting = 0\n",
            "; enable_extra_bridge_layer = disabled\n",
            "; enable_arc_fitting = 1\n",
        ),
        (
            "statistics",
            "; filament used [mm] = 262.34\n",
            "; estimated printing time (normal mode) = 8m 55s\n",
            "; filament used [mm] = 262.35\n",
        ),
    ] {
        mutations(CLASSIC, first, second, changed, label);
    }
}

#[test]
fn gcode_writer_arcs_and_do_export_multiobject_reject_six_synthetic_mutations() {
    // Classic has neither arcs nor multiple objects. These are comparator-only
    // snippets, not independently captured reference artifacts or producer passes.
    let arcs = format!("{ORCA}G2 X10 Y20 I1 J2 E.5 F3000\nG3 X30 Y40 R5 E.6\n");
    mutations(
        &arcs,
        "G2 X10 Y20 I1 J2 E.5 F3000\n",
        "G3 X30 Y40 R5 E.6\n",
        "G3 X10 Y20 I1 J2 E.5 F3000\n",
        "synthetic arcs",
    );
    let objects = format!(
        "{ORCA}; printing object alpha id:10 copy 0\n; stop printing object alpha id:10 copy 0\n; printing object beta id:20 copy 0\n; stop printing object beta id:20 copy 0\n"
    );
    mutations(
        &objects,
        "; printing object alpha id:10 copy 0\n",
        "; printing object beta id:20 copy 0\n",
        "; printing object alpha id:20 copy 0\n",
        "synthetic object identity",
    );
}

#[test]
fn generator_contract_eight_cases_validate_each_producer_independently() {
    let reference = format!("{ORCA}G1 X1\n");
    let actual = format!("{ARES}G1 X1\n");
    compare(reference.as_bytes(), actual.as_bytes()).unwrap();
    for (header, expected_name) in [(ORCA, "OrcaSlicer"), (ARES, "Ares")] {
        let invalid = [
            "G1 X1\n".as_bytes().to_vec(),
            format!("{header}{header}G1 X1\n").into_bytes(),
            format!("{}G1 X1\n", if header == ORCA { ARES } else { ORCA }).into_bytes(),
            format!("{}G1 X1\n", header.replace("2.4.2", "2.4.3")).into_bytes(),
            format!("{}G1 X1\n", header.replace(" at ", " ")).into_bytes(),
            format!("prefix {header}G1 X1\n").into_bytes(),
            [header.as_bytes(), &[0xff]].concat(),
        ];
        for bytes in invalid {
            let error = if header == ORCA {
                assert_ne!(bytes, reference.as_bytes());
                compare(&bytes, actual.as_bytes())
            } else {
                assert_ne!(bytes, actual.as_bytes());
                compare(reference.as_bytes(), &bytes)
            }
            .unwrap_err();
            assert!(
                error.contains(expected_name) || error.contains("utf-8"),
                "{error}"
            );
        }
    }
}

#[test]
fn do_export_preserves_six_stream_boundaries() {
    let reference = format!("{ORCA}G1 X1 Y2\n");
    let baseline = format!("{ARES}G1 X1 Y2\n");
    for body in [
        "G1  X1 Y2\n",
        "G1 X1 Y2\r\n",
        "G1 X1 Y2",
        "G1 X1 Y2\n\n",
        "G1 X1 Y2\nx",
        "G1 X1",
    ] {
        reject(
            &reference,
            &baseline,
            &format!("{ARES}{body}"),
            "stream boundary",
        );
    }
}
