use super::*;
use golden::{GeneratorKind, first_difference, normalize_one_generator_line};
use std::io::Cursor;

#[test]
fn fixture_contract_is_stable() {
    let project = project();
    let reference = reference();

    assert_eq!(sha256(&project), PROJECT_SHA256);
    assert_eq!(sha256(&reference), REFERENCE_SHA256);
    assert_eq!(
        zip::ZipArchive::new(Cursor::new(project)).unwrap().len(),
        15
    );
    assert_eq!(
        reference.iter().filter(|byte| **byte == b'\n').count(),
        269_330
    );
    assert_eq!(count_bytes(&reference, b"; CHANGE_LAYER\n"), 460);

    let normalized = normalize_one_generator_line(&reference, GeneratorKind::Orca).unwrap();
    assert_eq!(sha256(&normalized), NORMALIZED_REFERENCE_SHA256);
}

#[test]
fn generator_normalization_changes_only_the_validated_line() {
    let orca = b"before\n; generated by OrcaSlicer 2.4.2 on 2026-07-10 at 11:16:09\nafter\n";
    let ares = b"before\n; generated by Ares 2.4.2 on 2030-12-31 at 23:59:58\nafter\n";
    let expected = b"before\n; generated by <SLICER> 2.4.2 on <TIMESTAMP>\nafter\n";

    assert_eq!(
        normalize_one_generator_line(orca, GeneratorKind::Orca).unwrap(),
        expected
    );
    assert_eq!(
        normalize_one_generator_line(ares, GeneratorKind::Ares).unwrap(),
        expected
    );
}

#[test]
fn generator_normalization_requires_exactly_one_complete_utf8_line() {
    assert_eq!(
        normalize_one_generator_line(b"no generator line\n", GeneratorKind::Orca).unwrap_err(),
        "expected one OrcaSlicer generator line, found 0"
    );
    assert_eq!(
        normalize_one_generator_line(
            b"; generated by OrcaSlicer 2.4.2 on 2026-07-10 at 11:16:09\n; generated by OrcaSlicer 2.4.2 on 2026-07-10 at 11:16:10\n",
            GeneratorKind::Orca,
        )
        .unwrap_err(),
        "expected one OrcaSlicer generator line, found 2"
    );
    assert!(
        normalize_one_generator_line(
            b"prefix ; generated by OrcaSlicer 2.4.2 on 2026-07-10 at 11:16:09\n",
            GeneratorKind::Orca,
        )
        .is_err()
    );
    assert!(normalize_one_generator_line(&[0xff], GeneratorKind::Orca).is_err());
}

#[test]
fn generator_normalization_masks_vendor_branded_timestamp_lines() {
    let orca = b"; HEADER_BLOCK_START\n; generated by Creality_Print V7.0.1.4212 on 2026-9-13 at 5:31:39\n; total layer number: 125\n; generated by OrcaSlicer 2.4.2 on 2026-07-10 at 11:16:09\n";
    let ares = b"; HEADER_BLOCK_START\n; generated by Creality_Print V7.0.1.4212 on 2026-8-27 at 0:0:0\n; total layer number: 125\n; generated by Ares 2.4.2 on 2026-07-10 at 11:16:09\n";

    let normalized_orca = normalize_one_generator_line(orca, GeneratorKind::Orca).unwrap();
    let normalized_ares = normalize_one_generator_line(ares, GeneratorKind::Ares).unwrap();
    assert_eq!(normalized_orca, normalized_ares);
    assert!(
        String::from_utf8(normalized_orca)
            .unwrap()
            .contains("; generated by <SLICER> on <TIMESTAMP>")
    );
}

#[test]
fn first_difference_reports_bounded_three_line_context() {
    let expected = b"line1\nline2\nline3\nline4\nline5\n";
    let actual = b"line1\nline2\nLINE3\nline4\nline5\n";

    let difference = first_difference(expected, actual).unwrap().to_string();

    assert_eq!(
        difference,
        "first difference at byte 12 (line 3, column 1; expected 30 bytes, actual 30 bytes)\ncontext:\n  line 2: \"line2\"\n  line 3: expected \"line3\"; actual \"LINE3\"\n  line 4: \"line4\""
    );
    assert!(first_difference(expected, expected).is_none());
}

#[test]
fn first_difference_truncates_long_context_lines() {
    let expected = format!("before\n{}x\nafter\n", "a".repeat(10_000));
    let actual = format!("before\n{}y\nafter\n", "a".repeat(10_000));

    let difference = first_difference(expected.as_bytes(), actual.as_bytes())
        .unwrap()
        .to_string();

    assert!(difference.len() < 1_024);
    assert_eq!(
        difference
            .lines()
            .filter(|line| line.starts_with("  line "))
            .count(),
        3
    );
}
// Legacy selector suffix retained for callers; acceptance is strict bytes.
#[test]
fn project_matches_orca_242_semantically() {
    let temp = tempfile::tempdir().unwrap();
    let output = temp.path().join("actual.gcode");
    let before = local_now_to_second();
    assert_cmd::Command::cargo_bin("ares")
        .unwrap()
        .args([
            "slice",
            "-o",
            output.to_str().unwrap(),
            fixture_path("ksr_fdmtest_v4.project.3mf").to_str().unwrap(),
        ])
        .assert()
        .success();
    let after = local_now_to_second();
    let actual = std::fs::read(output).unwrap();
    let generated_at = generated_at(&actual);
    assert!(
        (before..=after).contains(&generated_at),
        "generator timestamp {generated_at} was outside {before}..={after}"
    );
    compare_actual(&actual);
}

#[test]
#[ignore = "invoked by the Playwright browser parity test"]
fn browser_output_matches_orca_242_semantically() {
    let path = std::env::var_os("ARES_BROWSER_GCODE").unwrap();
    let actual = fs::read(path).unwrap();
    compare_actual(&actual);
}

/// Diagnostic dump (env-gated): per-layer deposition lists for the Elegoo
/// parity case, to trace the missing gap-fill line. Run with
/// `ARES_ELEGOO_DUMP=<case-dir> cargo nextest run ... --ignored`.
#[test]
#[ignore = "diagnostic dump; requires ARES_ELEGOO_DUMP"]
fn dump_elegoo_depositions() {
    use semantic::parser as sem;
    let Some(dir) = std::env::var_os("ARES_ELEGOO_DUMP") else {
        panic!("set ARES_ELEGOO_DUMP to the case dir");
    };
    let dir = std::path::PathBuf::from(dir);
    let ares_bytes = std::fs::read("/tmp/elegoo.gcode").unwrap();
    let reference = std::fs::read(dir.join("plate_1.gcode")).unwrap();
    let ares = sem::parse(&ares_bytes).unwrap();
    let orca = sem::parse(&reference).unwrap();
    let mut dump = String::new();
    for (index, (a, o)) in ares.layers.iter().zip(&orca.layers).enumerate() {
        let layer = index + 1;
        if a.deposition.len() != o.deposition.len() {
            dump.push_str(&format!(
                "layer {layer}: deposition count ares {} orca {}\n",
                a.deposition.len(),
                o.deposition.len()
            ));
        }
        for (side, depositions) in [("ares", &a.deposition), ("orca", &o.deposition)] {
            let gap_depositions = depositions
                .iter()
                .enumerate()
                .filter(|(_, d)| d.feature.contains("Gap"));
            for (position, deposition) in gap_depositions {
                dump.push_str(&format!(
                    "layer {layer} {side}[{position}] {} w{} e{} start {:?} end {:?} f{}\n",
                    deposition.feature,
                    deposition.width,
                    deposition.extrusion,
                    deposition.motion.start,
                    deposition.motion.end,
                    deposition.feed
                ));
            }
        }
    }
    eprintln!("ELEGOO DUMP:\n{dump}");
    std::fs::write("/tmp/ares-review/elegoo_depositions.txt", &dump).unwrap();
}
