//! External behavior of `AvoidCrossingPerimeters::travel_to` and GCode travel emission.
//! Reference fixture generated by the OrcaSlicer AppImage, not source-token assertions.
use std::{fs, path::Path, process::Command};

#[test]
fn avoid_crossing_perimeters_preserves_ordered_xy_travel_commands() {
    let fixtures = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/avoid_crossing_travel");
    let temp = tempfile::tempdir().unwrap();
    let output = temp.path().join("actual.gcode");
    let binary =
        std::env::var_os("ARES_TRAVEL_BIN").unwrap_or_else(|| env!("CARGO_BIN_EXE_ares").into());
    let result = Command::new(binary)
        .arg("slice")
        .arg("-o")
        .arg(&output)
        .arg(fixtures.join("anchor.3mf"))
        .output()
        .unwrap();
    assert!(result.status.success(), "{result:?}");
    let actual = fs::read_to_string(output).unwrap();
    let expected = fs::read_to_string(fixtures.join("anchor.orca.gcode")).unwrap();
    let actual = xy_travels(&actual);
    let expected = xy_travels(&expected);
    assert_eq!(actual.len(), expected.len(), "XY travel command count");
    for (index, (actual, expected)) in actual.iter().zip(&expected).enumerate() {
        assert_eq!(actual, expected, "XY travel command {index}");
    }
}

fn xy_travels(gcode: &str) -> Vec<&str> {
    gcode
        .lines()
        .filter(|line| line.starts_with("G1 X") && !line.contains(" E"))
        .collect()
}
