//! `AvoidCrossingPerimeters::extend_for_closest_lines` through public CLI output.
use std::{fs, path::Path, process::Command};

#[test]
fn closest_line_extension_preserves_all_ordered_one_wall_xy_commands() {
    let (actual, expected) = slice_one_wall();
    let xy = |gcode: &str| {
        gcode
            .lines()
            .filter(|line| line.starts_with("G1 X") && !line.contains(" E"))
            .map(str::to_owned)
            .collect::<Vec<_>>()
    };
    let expected = xy(&expected);
    assert_eq!(expected.len(), 436);
    assert_eq!(
        xy(&actual),
        expected,
        "all ordered XY, including repeated corners"
    );
}

#[test]
fn closest_line_extension_matches_complete_one_wall_orca_artifact() {
    let (actual, expected) = slice_one_wall();
    assert_eq!(
        normalize_generator(&actual, "Ares"),
        normalize_generator(&expected, "OrcaSlicer"),
        "complete one-wall G-code, including whitespace, statistics and M73"
    );
}

fn slice_one_wall() -> (String, String) {
    let fixtures = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/avoid_crossing_travel");
    let temp = tempfile::tempdir().unwrap();
    let output = temp.path().join("actual.gcode");
    let binary =
        std::env::var_os("ARES_TRAVEL_BIN").unwrap_or_else(|| env!("CARGO_BIN_EXE_ares").into());
    let result = Command::new(binary)
        .arg("slice")
        .arg("-o")
        .arg(&output)
        .arg(fixtures.join("one-wall.3mf"))
        .output()
        .unwrap();
    assert!(result.status.success(), "{result:?}");
    (
        fs::read_to_string(output).unwrap(),
        fs::read_to_string(fixtures.join("one-wall.orca.gcode")).unwrap(),
    )
}

fn normalize_generator(gcode: &str, producer: &str) -> String {
    let pattern = regex::Regex::new(&format!(
        r"(?m)^; generated by {producer} 2\.4\.2 on (\d{{4}}-\d{{2}}-\d{{2}}) at (\d{{2}}:\d{{2}}:\d{{2}})$"
    ))
    .unwrap();
    let captures = pattern.captures_iter(gcode).collect::<Vec<_>>();
    assert_eq!(captures.len(), 1, "one valid {producer} generator line");
    format!("{}T{}", &captures[0][1], &captures[0][2])
        .parse::<jiff::civil::DateTime>()
        .unwrap();
    pattern
        .replace(gcode, "; generated by <GENERATOR>")
        .into_owned()
}
