use ares_core::GenerationMetadata;

fn normalize(bytes: &[u8], generator: &str) -> Result<Vec<u8>, String> {
    let text = std::str::from_utf8(bytes).map_err(|e| e.to_string())?;
    let pattern = regex::Regex::new(&format!(
        r"(?m)^; generated by {generator} 2\.4\.2 on (\d{{4}})-(\d{{2}})-(\d{{2}}) at (\d{{2}}):(\d{{2}}):(\d{{2}})$"
    )).unwrap();
    let matches: Vec<_> = pattern.captures_iter(text).collect();
    if matches.len() != 1 {
        return Err("expected exactly one validated generator line".into());
    }
    let fields: Vec<u16> = (1..=6).map(|i| matches[0][i].parse().unwrap()).collect();
    GenerationMetadata::new_local(
        fields[0],
        fields[1] as u8,
        fields[2] as u8,
        fields[3] as u8,
        fields[4] as u8,
        fields[5] as u8,
    )
    .map_err(|e| e.to_string())?;
    Ok(pattern
        .replace(text, "; generated by <VALIDATED>")
        .as_bytes()
        .to_vec())
}

pub(super) fn compare(reference: &[u8], actual: &[u8]) -> Result<(), String> {
    let reference = normalize(reference, "OrcaSlicer")?;
    let actual = normalize(actual, "Ares")?;
    if reference == actual {
        return Ok(());
    }
    let position = reference
        .iter()
        .zip(&actual)
        .position(|(a, b)| a != b)
        .unwrap_or(reference.len().min(actual.len()));
    Err(format!(
        "byte-strict mismatch at byte {position}; lengths {}/{}",
        reference.len(),
        actual.len()
    ))
}

#[test]
fn strict_comparison_rejects_travel_timing_config_and_statistics_changes() {
    let body = "G0 X1 Y2 F9000\n; estimated printing time = 1m\n; wall_generator = arachne\n; total filament used [g] = 1\n";
    let reference = format!("; generated by OrcaSlicer 2.4.2 on 2026-09-08 at 00:00:00\n{body}");
    let actual = format!("; generated by Ares 2.4.2 on 2026-09-09 at 01:02:03\n{body}");
    assert!(compare(reference.as_bytes(), actual.as_bytes()).is_ok());
    for (from, to) in [
        ("X1", "X2"),
        ("1m", "2m"),
        ("arachne", "classic"),
        ("[g] = 1", "[g] = 2"),
    ] {
        assert!(compare(reference.as_bytes(), actual.replace(from, to).as_bytes()).is_err());
    }
    assert!(
        compare(
            reference.as_bytes(),
            actual.replace("2026-09-09", "2026-99-99").as_bytes()
        )
        .is_err()
    );
}
