"""Repeat the bounded public-CLI evidence, not overall producer acceptance."""
import argparse
import datetime
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tarfile

BASE = '057f131b9ebb50538f865ffd770a89a1e79248dd'
PARTIAL_SHA256 = '408c9123b51b4d4c752bb443a68a52bdc55f6fa71b40571f59496c77261aace4'
APPIMAGE_SHA256 = '64515d01f887b4797105530751a3ad59b0fa8537fbe3a294c420e1e14bba3b60'
CASES = ['anchor', 'two-walls', 'wipe-off', 'solid-rectilinear']


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def normalize(data, producer):
    pattern = (rb'(?m)^; generated by ' + producer.encode()
               + rb' 2\.4\.2 on (\d{4}-\d{2}-\d{2}) at (\d{2}:\d{2}:\d{2})$')
    matches = list(re.finditer(pattern, data))
    assert len(matches) == 1, 'expected exactly one valid generator line'
    match = matches[0]
    datetime.datetime.fromisoformat((match[1] + b'T' + match[2]).decode())
    return re.sub(pattern, b'; validated generator', data)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, required=True)
    parser.add_argument('--candidate', required=True, help='explicit local revision')
    parser.add_argument('--partial', type=Path, required=True)
    parser.add_argument('--wrapper', type=Path, required=True)
    parser.add_argument('--appdir', type=Path, required=True)
    parser.add_argument('--lib-cache', type=Path, required=True)
    parser.add_argument('--evidence', type=Path, required=True, help='new external directory')
    args = parser.parse_args()
    evidence = args.evidence.resolve()
    evidence.mkdir(parents=True, exist_ok=False)
    assert digest(args.partial) == PARTIAL_SHA256
    assert digest(args.appdir / 'bin/orca-slicer') == APPIMAGE_SHA256
    shutil.copyfile(args.lib_cache, evidence / 'orca-libs.cache')
    shutil.copyfile(args.partial, evidence / 'logical-cursor.patch')
    commands = []

    def run(name, command, cwd=None, env=None):
        result = subprocess.run(command, cwd=cwd, env=env, capture_output=True, timeout=900)
        (evidence / (name + '.stdout')).write_bytes(result.stdout)
        (evidence / (name + '.stderr')).write_bytes(result.stderr)
        (evidence / (name + '.exit')).write_text(str(result.returncode) + '\n')
        commands.append(dict(command=[str(a) for a in command], cwd=str(cwd),
                             exit=result.returncode))
        (evidence / 'commands.json').write_text(json.dumps(commands, indent=2) + '\n')
        return result

    identities = dict(base=BASE, partial_sha256=PARTIAL_SHA256,
                      appimage_sha256=APPIMAGE_SHA256, wrapper_sha256=digest(args.wrapper))
    for label, revision, integration in [
        ('published-before', BASE, False), ('published-after', args.candidate, False),
        ('integration-before', BASE, True), ('integration-after', args.candidate, True),
    ]:
        archive = evidence / (label + '.tar')
        result = run(label + '-archive', ['git', 'archive', '--format=tar', revision], args.source)
        assert result.returncode == 0
        archive.write_bytes(result.stdout)
        identities[label + '_archive_sha256'] = digest(archive)
        source = evidence / label
        source.mkdir()
        with tarfile.open(archive) as tar:
            tar.extractall(source, filter='data')
        if integration:
            assert run(label + '-apply', ['git', 'apply', str(evidence / 'logical-cursor.patch')],
                       source).returncode == 0
        env = dict(os.environ, CARGO_TARGET_DIR=str(evidence / (label + '-target')))
        assert run(label + '-build', ['cargo', 'build', '-p', 'ares-cli'], source, env).returncode == 0
        executable = Path(env['CARGO_TARGET_DIR']) / 'debug/ares'
        identities[label + '_binary_sha256'] = digest(executable)
    (evidence / 'identities.json').write_text(json.dumps(identities, indent=2) + '\n')

    fixtures = evidence / 'published-after/tests/processor_seam_cache'
    comparisons = {}
    for case in CASES:
        directory = evidence / case
        directory.mkdir()
        reference_dir = directory / 'appimage'
        reference_dir.mkdir()
        env = dict(os.environ, ORCA_APPDIR=str(args.appdir.resolve()),
                   ORCA_LIB_CACHE=str(evidence / 'orca-libs.cache'))
        for key in ['HOME', 'XDG_CONFIG_HOME', 'XDG_CACHE_HOME', 'XDG_DATA_HOME']:
            path = directory / key
            path.mkdir()
            env[key] = str(path)
        project = fixtures / (case + '.3mf')
        assert run(case + '-appimage', [str(args.wrapper.resolve()), '--slice', '0',
                   '--outputdir', str(reference_dir), str(project)], env=env).returncode == 0
        reference = reference_dir / 'plate_1.gcode'
        expected = normalize(reference.read_bytes(), 'OrcaSlicer')
        assert expected == normalize((fixtures / (case + '.orca.gcode')).read_bytes(), 'OrcaSlicer')
        comparisons[case] = dict(input_sha256=digest(project), reference_sha256=digest(reference))
        for label in ['published-before', 'published-after', 'integration-before', 'integration-after']:
            executable = evidence / (label + '-target/debug/ares')
            output = directory / (label + '.gcode')
            assert run(case + '-' + label, [str(executable), 'slice', str(project), '-o',
                                          str(output)]).returncode == 0
            raw_diff = run(case + '-' + label + '-raw-diff', ['diff', '-u', str(reference), str(output)])
            assert raw_diff.returncode in [0, 1]
            status = int(normalize(output.read_bytes(), 'Ares') != expected)
            comparisons[case][label] = dict(strict_exit=status, sha256=digest(output))
            (directory / (label + '-strict.exit')).write_text(str(status) + '\n')
    (evidence / 'comparisons.json').write_text(json.dumps(comparisons, indent=2) + '\n')
    assert all(comparisons[c]['integration-before']['strict_exit'] == int(c in CASES[2:]) for c in CASES)
    assert all(comparisons[c]['integration-after']['strict_exit'] == 0 for c in CASES)
    print('Bounded integration passed; published CLI residuals remain in comparisons.json.')


if __name__ == '__main__':
    main()
